#!/usr/bin/env python

import sys

from my_module_mapping import MyPlugin_mapping
from rqt_gui.main import Main

plugin = 'rqt_mypkg_requirement_to_algorithm'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
